version: '3.8'
services:
  shopping_dashboard-application:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shopping_dashboard
      - SPRING_DATASOURCE_USERNAME=shop_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopping_dashboard
    healthcheck:
      test: "pg_isready -U shop_user -d shopping_dashboard"
      interval: 5s
      timeout: 50s
      retries: 10

volumes:
  db_data: